pickAssets fix on iOS14
fluttercandies/flutter_wechat_assets_picker pull request #149
Opened 2021-06-11 16:45 UTC by Araniko

PhotoManager.requestPermission is deprecated and does not account for the newly introduced "limited" permission in iOS14, which caused the pickAssets-method to always return null. This fix checks for the new permission.

2021-06-11 18:27 UTC, AlexV525 requested changes
Thanks for the contribution. The main idea of this PR is valid, but we need to tweak some details before it gets merged.

2021-06-11 18:27 UTC, AlexV525 commented on lib/src/widget/asset_picker.dart
> +  static Future<List<AssetEntity>?> pickAssets(BuildContext context, {
Please revert all format changes.

2021-06-11 18:27 UTC, AlexV525 commented on lib/src/widget/asset_picker.dart
>        if (isPermissionGranted) {
Don't use duplicate await.

```suggestion
      final PermissionState _ps = await PhotoManager.requestPermissionExtend();
      if (_ps == PermissionState.authorized || _ps == PermissionState.limited) {
```

2021-06-11 18:29 UTC, AlexV525 commented
Also we need to bump the version constraint of `photo_manager` in `pubspec.yaml` for consistency.

2021-06-12 05:40 UTC, AlexV525 commented
Nvm, I'll fix this with a commit.

2021-06-12 05:40 UTC, closed without merging

2021-06-14 15:52 UTC, Araniko commented
Thanks!